apiVersion: v1
kind: ConfigMap
metadata:
  name: internconnect-config
  namespace: internconnect
data:
  PORT: "7000"
  NODE_ENV: "production"
  # Frontend API URL — points to VPS backend
  EXPO_PUBLIC_API_URL: "http://38.242.246.126:7000/api"
